name: analyzer_formatter
description: Tool for Dart Analyzer result formatting
version: 0.1.2
homepage: https://github.com/WhisperArts/analyzer-formatter

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  path: ^1.7.0
  xml: ^4.5.1

dev_dependencies:
  test: ^1.14.4

  effective_dart: ^1.3.0
