name: analyzer_formatter
description: Dart Analyzer result formatter
version: 0.2.0
homepage: https://github.com/WhisperArts/analyzer-formatter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  xml: ^5.0.2

dev_dependencies:
  test: ^1.16.7

  effective_dart: ^1.3.1
